"""add ai_fixes and user_settings tables

Revision ID: 7a529fe679fb
Revises: 95ff39ebd128
Create Date: 2026-07-02 17:08:12.648732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a529fe679fb'
down_revision: Union[str, None] = '95ff39ebd128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('incident_alerts', sa.Boolean(), nullable=False),
    sa.Column('pr_risk_alerts', sa.Boolean(), nullable=False),
    sa.Column('weekly_digest', sa.Boolean(), nullable=False),
    sa.Column('cost_alerts', sa.Boolean(), nullable=False),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('auto_fix_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_recovery_enabled', sa.Boolean(), nullable=False),
    sa.Column('risk_sensitivity', sa.String(length=20), nullable=False),
    sa.Column('min_confidence_threshold', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ai_fixes',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('pull_request_number', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suggested_patch', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_fixes')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
