"""add ai_reviews table

Revision ID: aaa82b55a106
Revises: 0466f134d4fa
Create Date: 2026-07-02 14:24:17.362288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa82b55a106'
down_revision: Union[str, None] = '0466f134d4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reviews',
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('pull_request_number', sa.Integer(), nullable=False),
    sa.Column('review_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('deployment_confidence', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.String(length=50), nullable=False),
    sa.Column('technical_debt_summary', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_reviews')
    # ### end Alembic commands ###
